import { phonemes } from "./phonemes"

export const categories = {
    es: {
        word: 'Palabra',
        phoneme: 'Fonema',
        both: 'Palabra/Fonema'
    },
    en: {
        word: 'Word',
        phoneme: 'Phoneme',
        both: 'Word/Phoneme'
    }
}

export const dificulty = {
    es: [
        'Complejo',
        'Difícil',
        'Medio',
        'Sencillo'
    ],
    en: [
        'Complex',
        'Hard',
        'Medium',
        'Easy'
    ]
}

export const gestures = { 
    es: {
       'a' : {
            phoneme: 'a',
            placeholder: '/src/assets/gestures/placeholders/Saludo.webp',
            gif: '/src/assets/gestures/gifs/Saludo.gif',
            spelling: phonemes['a'].associated,
            name: 'Saludo',
            nature: 'Fonema',
            category: 'PF',
            dificulty: 3,
            description: 'Con la punta de los dedos tocando la sien se extiende el brazo quedando horizontal a la altura del hombro',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Saludo.webp',
            animation: '/src/assets/gestures/animations/Saludo.webm'
        },
        'óla' : {
            phoneme: 'óla',
            placeholder: '/src/assets/gestures/placeholders/Saludo.webp',
            gif: '/src/assets/gestures/gifs/Saludo.gif',
            spelling: ['hola'],
            name: 'Saludo',
            nature: 'Palabra',
            category: 'PF',
            dificulty: 3,
            description: 'Con la punta de los dedos tocando la sien se extiende el brazo quedando horizontal a la altura del hombro',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Saludo.webp',
            animation: '/src/assets/gestures/animations/Saludo.webm'
        },
        'e' : {
            phoneme: 'e',
            placeholder: '/src/assets/gestures/placeholders/Agradecimiento.webp',
            gif: '/src/assets/gestures/gifs/Agradecimiento.gif',
            spelling: phonemes['e'].associated,
            name: 'Agradecimiento',
            nature: 'Fonema',
            category: 'PF',
            dificulty: 3,
            description: 'Con la punta de los dedos tocando la barbilla se extiende completamente el brazo hacia el frente y a la altura del pecho',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Agradecimiento.webp',
            animation: '/src/assets/gestures/animations/Agradecimiento.webm'
        },
        'gɾasias' : {
            phoneme: 'gɾasias',
            placeholder: '/src/assets/gestures/placeholders/Agradecimiento.webp',
            gif: '/src/assets/gestures/gifs/Agradecimiento.gif',
            spelling: ['gracias'],
            name: 'Agradecimiento',
            nature: 'Palabra',
            category: 'PF',
            dificulty: 3,
            description: 'Con la punta de los dedos tocando la barbilla se extiende completamente el brazo hacia el frente y a la altura del pecho',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Agradecimiento.webp',
            animation: '/src/assets/gestures/animations/Agradecimiento.webm'
        },
        'i' : {
            phoneme: 'i',
            placeholder: '/src/assets/gestures/placeholders/Elevar.webp',
            gif: '/src/assets/gestures/gifs/Elevar.gif',
            spelling: phonemes['i'].associated,
            name: 'Elevación',
            nature: 'Fonema',
            category: 'PF',
            dificulty: 3,
            description: 'Partiendo a la altura de la cadera y con la palma hacia arriba, se eleva verticalmente la mano aproximadamente a la altura de la barbilla',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Elevar.webp',
            animation: '/src/assets/gestures/animations/Elevar.webm'
        },
        'bien' : {
            phoneme: 'bien',
            placeholder: '/src/assets/gestures/placeholders/Elevar.webp',
            gif: '/src/assets/gestures/gifs/Elevar.gif',
            spelling: ['bien'],
            name: 'Elevación',
            nature: 'Palabra',
            category: 'PF',
            dificulty: 3,
            description: 'Partiendo a la altura de la cadera y con la palma hacia arriba, se eleva verticalmente la mano aproximadamente a la altura de la barbilla',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Elevar.webp',
            animation: '/src/assets/gestures/animations/Elevar.webm'
        },
        'o' : {
            phoneme: 'o',
            placeholder: '/src/assets/gestures/placeholders/Circunferencia.webp',
            gif: '/src/assets/gestures/gifs/Circunferencia.gif',
            spelling: phonemes['o'].associated,
            name: 'Circunferencia',
            nature: 'Fonema',
            category: 'PF',
            dificulty: 2,
            description: 'Con los dedos extendidos y apuntando hacia arriba se dibuja una circunferencia iniciando el recorrido hacia adentro (hacia al pecho).',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Circunferencia.webp',
            animation: '/src/assets/gestures/animations/Circunferencia.webm'
        },
        'kome' : {
            phoneme: 'komeɾ',
            placeholder: '/src/assets/gestures/placeholders/Circunferencia.webp',
            gif: '/src/assets/gestures/gifs/Circunferencia.gif',
            spelling: ['comer'],
            name: 'Circunferencia',
            nature: 'Palabra',
            category: 'PF',
            dificulty: 2,
            description: 'Con los dedos extendidos y apuntando hacia arriba se dibuja una circunferencia iniciando el recorrido hacia adentro (hacia al pecho).',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Circunferencia.webp',
            animation: '/src/assets/gestures/animations/Circunferencia.webm'
        },
        'u' : {
            phoneme: 'u',
            placeholder: '/src/assets/gestures/placeholders/Balanceo.webp',
            gif: '/src/assets/gestures/gifs/Balanceo.gif',
            spelling: phonemes['u'].associated,
            name: 'Balanceo',
            nature: 'Fonema',
            category: 'PF',
            dificulty: 2,
            description: 'Partiendo de la altura de las costillas con el codo ligeramente más flexionado de 90 grados y los dedos apuntando al frente, se dibuja una depresión hacia la izquierda (como un tazón poco profundo) y se regresa con una depresión hacia la derecha',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Balanceo.webp',
            animation: '/src/assets/gestures/animations/Balanceo.webm'
        },
        'kaminaɾ' : {
            phoneme: 'kaminaɾ',
            placeholder: '/src/assets/gestures/placeholders/Balanceo.webp',
            gif: '/src/assets/gestures/gifs/Balanceo.gif',
            spelling: ['caminar'],
            name: 'Balanceo',
            nature: 'Palabra',
            category: 'PF',
            dificulty: 2,
            description: 'Partiendo de la altura de las costillas con el codo ligeramente más flexionado de 90 grados y los dedos apuntando al frente, se dibuja una depresión hacia la izquierda (como un tazón poco profundo) y se regresa con una depresión hacia la derecha',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Balanceo.webp',
            animation: '/src/assets/gestures/animations/Balanceo.webm'
        },
        'p' : {
            phoneme: 'p',
            placeholder: '/src/assets/gestures/placeholders/Doble_golpe.webp',
            gif: '/src/assets/gestures/gifs/Doble_golpe.gif',
            spelling: phonemes['p'].associated,
            name: 'Doble golpe',
            nature: 'Fonema',
            category: 'PF',
            dificulty: 3,
            description: 'Con la mano derecha en puño y a la altura del corazón, y la izquierda con la palma hacia arriba a la altura del ombligo, se baja la derecha golpeando dos veces en la mano izquierda y regresa a la altura original',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Doble_golpe.webp',
            animation: '/src/assets/gestures/animations/Doble_golpe.webm'
        },
        'kuándo'  : {
            phoneme: 'kuándo',
            placeholder: '/src/assets/gestures/placeholders/Doble_golpe.webp',
            gif: '/src/assets/gestures/gifs/Doble_golpe.gif',
            spelling: ['¿Cuándo?'],
            name: 'Doble golpe',
            nature: 'Palabra',
            category: 'PF',
            dificulty: 3,
            description: 'Con la mano derecha en puño y a la altura del corazón, y la izquierda con la palma hacia arriba a la altura del ombligo, se baja la derecha golpeando dos veces en la mano izquierda y regresa a la altura original',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Doble_golpe.webp',
            animation: '/src/assets/gestures/animations/Doble_golpe.webm'
        },
        'b' : {
            phoneme: 'b',
            placeholder: '/src/assets/gestures/placeholders/Vamos.webp',
            gif: '/src/assets/gestures/gifs/Vamos.gif',
            spelling: phonemes['b'].associated,
            name: 'Indicación',
            nature: 'Fonema',
            category: 'PF',
            dificulty: 2,
            description: 'Con la mano derecha a la altura de la cadera y la izquierda a la altura de la barbilla, se realiza un movimiento como corte vertical en sentidos contrarios, la derecha sube a la barbilla y la izquierda baja a la cadera. Por un instante a medio camino ambas manos se rozan',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Vamos.webp',
            animation: '/src/assets/gestures/animations/Vamos.webm'
        },
        'maɲana' : {
            phoneme: 'maɲana',
            placeholder: '/src/assets/gestures/placeholders/Vamos.webp',
            gif: '/src/assets/gestures/gifs/Vamos.gif',
            spelling: ['mañana'],
            name: 'Indicación',
            nature: 'Palabra',
            category: 'PF',
            dificulty: 2,
            description: 'Con la mano derecha a la altura de la cadera y la izquierda a la altura de la barbilla, se realiza un movimiento como corte vertical en sentidos contrarios, la derecha sube a la barbilla y la izquierda baja a la cadera. Por un instante a medio camino ambas manos se rozan',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Vamos.webp',
            animation: '/src/assets/gestures/animations/Vamos.webm'
        },
        't' : {
            phoneme: 't',
            placeholder: '/src/assets/gestures/placeholders/Corte.webp',
            gif: '/src/assets/gestures/gifs/Corte.gif',
            spelling: phonemes['t'].associated,
            name: 'Corte',
            nature: 'Fonema',
            category: 'PF',
            dificulty: 3,
            description: 'Con la mano derecha tocando el costado izquierdo de la cadera y la palma viendo hacia abajo, se realiza un corte horizontal hacia la derecha con una pequeña inclinación hacia arriba',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Corte.webp',
            animation: '/src/assets/gestures/animations/Corte.webm'
        },
        'aseɾ' : {
            phoneme: 'aseɾ',
            placeholder: '/src/assets/gestures/placeholders/Corte.webp',
            gif: '/src/assets/gestures/gifs/Corte.gif',
            spelling: ['hacer'],
            name: 'Corte',
            nature: 'Palabra',
            category: 'PF',
            dificulty: 3,
            description: 'Con la mano derecha tocando el costado izquierdo de la cadera y la palma viendo hacia abajo, se realiza un corte horizontal hacia la derecha con una pequeña inclinación hacia arriba',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Corte.webp',
            animation: '/src/assets/gestures/animations/Corte.webm'
        },
        'd' : {
            phoneme: 'd',
            placeholder: '/src/assets/gestures/placeholders/Idear.webp',
            gif: '/src/assets/gestures/gifs/Idear.gif',
            spelling: phonemes['d'].associated,
            name: 'Pensamiento',
            nature: 'Fonema',
            category: 'PF',
            dificulty: 3,
            description: 'Con la palma de la mano derecha entornada a medio camino hacia el pecho y a la altura del corazón, sube tocando con las yemas de los dedos la sección derecha de la frente y luego extiende hacia el frente y ligeramente hacia afuera para terminar con los dedos extendidos apuntando al frente',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Idear.webp',
            animation: '/src/assets/gestures/animations/Idear.webm'
        },
        'pensaɾ' : {
            phoneme: 'pensaɾ',
            placeholder: '/src/assets/gestures/placeholders/Idear.webp',
            gif: '/src/assets/gestures/gifs/Idear.gif',
            spelling: ['pensar'],
            name: 'Pensamiento',
            nature: 'Palabra',
            category: 'PF',
            dificulty: 3,
            description: 'Con la palma de la mano derecha entornada a medio camino hacia el pecho y a la altura del corazón, sube tocando con las yemas de los dedos la sección derecha de la frente y luego extiende hacia el frente y ligeramente hacia afuera para terminar con los dedos extendidos apuntando al frente',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Idear.webp',
            animation: '/src/assets/gestures/animations/Idear.webm'
        },
        'k' : {
            phoneme: 'k',
            placeholder: '/src/assets/gestures/placeholders/Exclamacion.webp',
            gif: '/src/assets/gestures/gifs/Exclamacion.gif',
            spelling: phonemes['k'].associated,
            name: 'Exclamación',
            nature: 'Fonema',
            category: 'PF',
            dificulty: 3,
            description: 'Con las yemas de los dedos tocándose y las palmas mirando hacia el estómago, se abren los brazos en sentido contrario de manera que las palmas se entornan ligeramente hacia arriba y hacia afuera',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Exclamacion.webp',
            animation: '/src/assets/gestures/animations/Exclamacion.webm'
        },
        'poɾ ké' : {
            phoneme: 'poɾ ké',
            placeholder: '/src/assets/gestures/placeholders/Exclamacion.webp',
            gif: '/src/assets/gestures/gifs/Exclamacion.gif',
            spelling: ['¿Por qué?'],
            name: 'Exclamación',
            nature: 'Palabra',
            category: 'PF',
            dificulty: 3,
            description: 'Con las yemas de los dedos tocándose y las palmas mirando hacia el estómago, se abren los brazos en sentido contrario de manera que las palmas se entornan ligeramente hacia arriba y hacia afuera',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Exclamacion.webp',
            animation: '/src/assets/gestures/animations/Exclamacion.webm'
        },
        'g' : {
            phoneme: 'g',
            placeholder: '/src/assets/gestures/placeholders/Medio_circulo.webp',
            gif: '/src/assets/gestures/gifs/Medio_circulo.gif',
            spelling: phonemes['g'].associated,
            name: 'Medio círculo',
            nature: 'Fonema',
            category: 'PF',
            dificulty: 3,
            description: 'Con las yemas de los dedos tocándose y las palmas mirando hacia adentro a la altura del abdomen, se marca un medio círculo con cada mano para finalizar tocandose las yemas de los dedo otra vez a la altura de la barbilla',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Medio_circulo.webp',
            animation: '/src/assets/gestures/animations/Medio_circulo.webm'
        },
        'asta' : {
            phoneme: 'asta',
            placeholder: '/src/assets/gestures/placeholders/Medio_circulo.webp',
            gif: '/src/assets/gestures/gifs/Medio_circulo.gif',
            spelling: ['hasta'],
            name: 'Medio círculo',
            nature: 'Palabra',
            category: 'PF',
            dificulty: 3,
            description: 'Con las yemas de los dedos tocándose y las palmas mirando hacia adentro a la altura del abdomen, se marca un medio círculo con cada mano para finalizar tocandose las yemas de los dedo otra vez a la altura de la barbilla',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Medio_circulo.webp',
            animation: '/src/assets/gestures/animations/Medio_circulo.webm'
        },
        'ʧ' : {
            phoneme: 'ʧ',
            placeholder: '/src/assets/gestures/placeholders/Aplauso_doble.webp',
            gif: '/src/assets/gestures/gifs/Aplauso_doble.gif',
            spelling: phonemes['ʧ'].associated,
            name: 'Aplauso doble',
            nature: 'Fonema',
            category: 'PF',
            dificulty: 3,
            description: 'Con las manos en los costados se realizan 2 aplausos y se termina el movimiento con las manos juntas después del segundo aplauso',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Aplauso_doble.webp',
            animation: '/src/assets/gestures/animations/Aplauso_doble.webm'
        },
        'adios' : {
            phoneme: 'adios',
            placeholder: '/src/assets/gestures/placeholders/Aplauso_doble.webp',
            gif: '/src/assets/gestures/gifs/Aplauso_doble.gif',
            spelling: ['adiós'],
            name: 'Aplauso doble',
            nature: 'Palabra',
            category: 'PF',
            dificulty: 3,
            description: 'Con las manos en los costados se realizan 2 aplausos y se termina el movimiento con las manos juntas después del segundo aplauso',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Aplauso_doble.webp',
            animation: '/src/assets/gestures/animations/Aplauso_doble.webm'
        },
        'f' : {
            phoneme: 'f',
            spelling: phonemes['f'].associated,
            placeholder: '/src/assets/gestures/placeholders/Chop_chop.webp',
            gif: '/src/assets/gestures/gifs/Chop_chop.gif',
            name: 'Chop Chop',
            nature: 'Fonema',
            category: 'PF',
            dificulty: 3,
            description: 'Con la mano a 45 grados y tocando la barbilla se realizan 2 movimientos como cortes hacia al frente',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Chop_chop.webp',
            animation: '/src/assets/gestures/animations/Chop_chop.webm'
        },
        'aoɾa' : {
            phoneme: 'aoɾa',
            spelling: ['ahora'],
            placeholder: '/src/assets/gestures/placeholders/Chop_chop.webp',
            gif: '/src/assets/gestures/gifs/Chop_chop.gif',
            name: 'Chop Chop',
            nature: 'Palabra',
            category: 'PF',
            dificulty: 3,
            description: 'Con la mano a 45 grados y tocando la barbilla se realizan 2 movimientos como cortes hacia al frente',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Chop_chop.webp',
            animation: '/src/assets/gestures/animations/Chop_chop.webm'
        },
        's' : {
            phoneme: 's',
            placeholder: '/src/assets/gestures/placeholders/Sentimiento.webp',
            gif: '/src/assets/gestures/gifs/Sentimiento.gif',
            spelling: phonemes['s'].associated,
            name: 'Sentimiento',
            nature: 'Fonema',
            category: 'PF',
            dificulty: 3,
            description: 'Tocando con la puntas de los dedos el pecho al nivel del corazón se marca un círculo iniciando a la izquierda',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Sentimiento.webp',
            animation: '/src/assets/gestures/animations/Sentimiento.webm'
        },
        'sentiɾ' : {
            phoneme: 'sentiɾ',
            placeholder: '/src/assets/gestures/placeholders/Sentimiento.webp',
            gif: '/src/assets/gestures/gifs/Sentimiento.gif',
            spelling: ['sentir'],
            name: 'Sentimiento',
            nature: 'Palabra',
            category: 'PF',
            dificulty: 3,
            description: 'Tocando con la puntas de los dedos el pecho al nivel del corazón se marca un círculo iniciando a la izquierda',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Sentimiento.webp',
            animation: '/src/assets/gestures/animations/Sentimiento.webm'
        },
        'x' : {
            phoneme: 'x',
            placeholder: '/src/assets/gestures/placeholders/Cruzar.webp',
            gif: '/src/assets/gestures/gifs/Cruzar.gif',
            spelling: phonemes['x'].associated,
            name: 'Entrecruzado',
            nature: 'Fonema',
            category: 'F',
            dificulty: 1,
            description: 'Se dibuja una x partiendo de la altura del hombro derecho, después al costado de la cadera izquierda, sube a la altura del hombro izquierdo y finaliza en el costado derecho de la cadera',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Cruzar.webp',
            animation: '/src/assets/gestures/animations/Cruzar.webm'
        },
        'komo' : {
            phoneme: 'komo',
            placeholder: '/src/assets/gestures/placeholders/Cruzar.webp',
            gif: '/src/assets/gestures/gifs/Cruzar.gif',
            spelling: ['¿Cómo?'],
            name: 'Entrecruzado',
            nature: 'Palabra',
            category: 'F',
            dificulty: 1,
            description: 'Se dibuja una x partiendo de la altura del hombro derecho, después al costado de la cadera izquierda, sube a la altura del hombro izquierdo y finaliza en el costado derecho de la cadera',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Cruzar.webp',
            animation: '/src/assets/gestures/animations/Cruzar.webm'
        },
        'j' : {
            phoneme: 'j',
            placeholder: '/src/assets/gestures/placeholders/Yo.webp',
            gif: '/src/assets/gestures/gifs/Yo.gif',
            spelling: phonemes['j'].associated,
            name: 'Propio',
            nature: 'Fonema',
            category: 'PF',
            dificulty: 3,
            description: 'Con los dedos extendidos y el brazo tocando el bolsillo derecho, se sube el brazo y se toca el pecho a la altura del corazón',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Yo.webp',
            animation: '/src/assets/gestures/animations/Yo.webm'
        },
        'jo' : {
            phoneme: 'jo',
            placeholder: '/src/assets/gestures/placeholders/Yo.webp',
            gif: '/src/assets/gestures/gifs/Yo.gif',
            spelling: ['yo'],
            name: 'Propio',
            nature: 'Palabra',
            category: 'PF',
            dificulty: 3,
            description: 'Con los dedos extendidos y el brazo tocando el bolsillo derecho, se sube el brazo y se toca el pecho a la altura del corazón',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Yo.webp',
            animation: '/src/assets/gestures/animations/Yo.webm'
        },
        'm' : {
            phoneme: 'm',
            placeholder: '/src/assets/gestures/placeholders/Costados.webp',
            gif: '/src/assets/gestures/gifs/Costados.gif',
            spelling: phonemes['m'].associated,
            name: 'Costados',
            nature: 'Fonema',
            category: 'F',
            dificulty: 2,
            description: 'Con la mano apuntando al frente y a la mitad del pecho, se marca un cuarto de arco hacia la izquierda bajando a la altura de las costillas y se regresa con un medio arco a la derecha que sube a la altura del pecho y finaliza en las costillas derechas',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Costados.webp',
            animation: '/src/assets/gestures/animations/Costados.webm'
        },
        'donde' : {
            phoneme: 'donde',
            placeholder: '/src/assets/gestures/placeholders/Costados.webp',
            gif: '/src/assets/gestures/gifs/Costados.gif',
            spelling: ['¿Dónde?'],
            name: 'Costados',
            nature: 'Palabra',
            category: 'F',
            dificulty: 2,
            description: 'Con la mano apuntando al frente y a la mitad del pecho, se marca un cuarto de arco hacia la izquierda bajando a la altura de las costillas y se regresa con un medio arco a la derecha que sube a la altura del pecho y finaliza en las costillas derechas',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Costados.webp',
            animation: '/src/assets/gestures/animations/Costados.webm'
        },
        'n' : {
            phoneme: 'n',
            placeholder: '/src/assets/gestures/placeholders/Agitado.webp',
            gif: '/src/assets/gestures/gifs/Agitado.gif',
            spelling: phonemes['n'].associated,
            name: 'Agitado',
            nature: 'Fonema',
            category: 'PF',
            dificulty: 3,
            description: 'Con la mano a la altura del hombro derecho, se agita dos veces de derecha a izquierda y de regreso',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Agitado.webp',
            animation: '/src/assets/gestures/animations/Agitado.webm'
        },
        'tiempo' : {
            phoneme: 'tiempo',
            placeholder: '/src/assets/gestures/placeholders/Agitado.webp',
            gif: '/src/assets/gestures/gifs/Agitado.gif',
            spelling: ['tiempo'],
            name: 'Agitado',
            nature: 'Palabra',
            category: 'PF',
            dificulty: 3,
            description: 'Con la mano a la altura del hombro derecho, se agita dos veces de derecha a izquierda y de regreso',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Agitado.webp',
            animation: '/src/assets/gestures/animations/Agitado.webm'
        },
        'ɲ' : {
            phoneme: 'ɲ',
            placeholder: '/src/assets/gestures/placeholders/Medio_corazon.webp',
            gif: '/src/assets/gestures/gifs/Medio_corazon.gif',
            spelling: phonemes['ɲ'].associated,
            name: 'Medio corazón',
            nature: 'Fonema',
            category: 'PF',
            dificulty: 2,
            description: 'Se parte de la mitad del pecho y se realiza un semicírculo hacia afuera a la altura del inicio de las costilla y el hombro, después de baja con una inclinación de 45 grados hacia el ombligo',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Medio_corazon.webp',
            animation: '/src/assets/gestures/animations/Medio_corazon.webm'
        },
        'keɾeɾ' : {
            phoneme: 'keɾeɾ',
            placeholder: '/src/assets/gestures/placeholders/Medio_corazon.webp',
            gif: '/src/assets/gestures/gifs/Medio_corazon.gif',
            spelling: ['querer'],
            name: 'Medio corazón',
            nature: 'Palabra',
            category: 'PF',
            dificulty: 2,
            description: 'Se parte de la mitad del pecho y se realiza un semicírculo hacia afuera a la altura del inicio de las costilla y el hombro, después de baja con una inclinación de 45 grados hacia el ombligo',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Medio_corazon.webp',
            animation: '/src/assets/gestures/animations/Medio_corazon.webm'
        },
        'l' : {
            phoneme: 'l',
            placeholder: '/src/assets/gestures/placeholders/Doble_latido.webp',
            gif: '/src/assets/gestures/gifs/Doble_latido.gif',
            spelling: phonemes['l'].associated,
            name: 'Latido doble',
            nature: 'Fonema',
            category: 'PF',
            dificulty: 3,
            description: 'Con la palma tocando el pecho a la altura del corazón, se despega unos centímetros y se vuelve a tocar en 2 ocasiones',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Doble_latido.webp',
            animation: '/src/assets/gestures/animations/Doble_latido.webm'
        },
        'teneɾ' : {
            phoneme: 'teneɾ',
            placeholder: '/src/assets/gestures/placeholders/Doble_latido.webp',
            gif: '/src/assets/gestures/gifs/Doble_latido.gif',
            spelling: ['tener'],
            name: 'Latido doble',
            nature: 'Palabra',
            category: 'PF',
            dificulty: 3,
            description: 'Con la palma tocando el pecho a la altura del corazón, se despega unos centímetros y se vuelve a tocar en 2 ocasiones',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Doble_latido.webp',
            animation: '/src/assets/gestures/animations/Doble_latido.webm'
        },
        'ɾ' : {
            phoneme: 'ɾ',
            placeholder: '/src/assets/gestures/placeholders/Revolver.webp',
            gif: '/src/assets/gestures/gifs/Revolver.gif',
            spelling: phonemes['ɾ'].associated,
            name: 'Meneo',
            nature: 'Fonema',
            category: 'PF',
            dificulty: 2,
            description: 'Con la mano derecha arriba y la izquierda abajo, se giran en sentidos contrarios(hacia afuera y hacia atrás respectivamente) completando una circunferencia y vuelven a la misma altura en la que se empezó',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Revolver.webp',
            animation: '/src/assets/gestures/animations/Revolver.webm'
        },
        'todo' : {
            phoneme: 'todo',
            placeholder: '/src/assets/gestures/placeholders/Revolver.webp',
            gif: '/src/assets/gestures/gifs/Revolver.gif',
            spelling: ['todo'],
            name: 'Meneo',
            nature: 'Palabra',
            category: 'PF',
            dificulty: 2,
            description: 'Con la mano derecha arriba y la izquierda abajo, se giran en sentidos contrarios(hacia afuera y hacia atrás respectivamente) completando una circunferencia y vuelven a la misma altura en la que se empezó',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Revolver.webp',
            animation: '/src/assets/gestures/animations/Revolver.webm'
        },
        'r' : {
            phoneme: 'r',
            placeholder: '/src/assets/gestures/placeholders/Recorrer.webp',
            gif: '/src/assets/gestures/gifs/Recorrer.gif',
            spelling: phonemes['r'].associated,
            name: 'Impulso',
            nature: 'Fonema',
            category: 'PF',
            dificulty: 3,
            description: 'Con la palma mirando al frente y cerca del pecho, se hace un gesto de empujar hacia adelante',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Recorrer.webp',
            animation: '/src/assets/gestures/animations/Recorrer.webm'
        },
        'peɾo' : {
            phoneme: 'peɾo',
            placeholder: '/src/assets/gestures/placeholders/Recorrer.webp',
            gif: '/src/assets/gestures/gifs/Recorrer.gif',
            spelling: ['pero'],
            name: 'Impulso',
            nature: 'Palabra',
            category: 'PF',
            dificulty: 3,
            description: 'Con la palma mirando al frente y cerca del pecho, se hace un gesto de empujar hacia adelante',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Recorrer.webp',
            animation: '/src/assets/gestures/animations/Recorrer.webm'
        },
    },
    en: {
       'a' : {
            phoneme: 'a',
            placeholder: '/src/assets/gestures/placeholders/Saludo.webp',
            gif: '/src/assets/gestures/gifs/Saludo.gif',
            spelling: phonemes['a'].associated,
            name: 'Saludo',
            nature: 'Phoneme',
            category: 'WP',
            dificulty: 3,
            description: 'Con la punta de los dedos tocando la sien se extiende el brazo quedando horizontal a la altura del hombro',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Saludo.webp',
            animation: '/src/assets/gestures/animations/Saludo.webm'
        },
        'óla' : {
            phoneme: 'óla',
            placeholder: '/src/assets/gestures/placeholders/Saludo.webp',
            gif: '/src/assets/gestures/gifs/Saludo.gif',
            spelling: ['hola'],
            name: 'Saludo',
            nature: 'word',
            category: 'WP',
            dificulty: 3,
            description: 'Con la punta de los dedos tocando la sien se extiende el brazo quedando horizontal a la altura del hombro',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Saludo.webp',
            animation: '/src/assets/gestures/animations/Saludo.webm'
        },
        'e' : {
            phoneme: 'e',
            placeholder: '/src/assets/gestures/placeholders/Agradecimiento.webp',
            gif: '/src/assets/gestures/gifs/Agradecimiento.gif',
            spelling: phonemes['e'].associated,
            name: 'Agradecimiento',
            nature: 'phoneme',
            category: 'WP',
            dificulty: 3,
            description: 'Con la punta de los dedos tocando la barbilla se extiende completamente el brazo hacia el frente y a la altura del pecho',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Agradecimiento.webp',
            animation: '/src/assets/gestures/animations/Agradecimiento.webm'
        },
        'gɾasias' : {
            phoneme: 'gɾasias',
            placeholder: '/src/assets/gestures/placeholders/Agradecimiento.webp',
            gif: '/src/assets/gestures/gifs/Agradecimiento.gif',
            spelling: ['gracias'],
            name: 'Agradecimiento',
            nature: 'word',
            category: 'WP',
            dificulty: 3,
            description: 'Con la punta de los dedos tocando la barbilla se extiende completamente el brazo hacia el frente y a la altura del pecho',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Agradecimiento.webp',
            animation: '/src/assets/gestures/animations/Agradecimiento.webm'
        },
        'i' : {
            phoneme: 'i',
            placeholder: '/src/assets/gestures/placeholders/Elevar.webp',
            gif: '/src/assets/gestures/gifs/Elevar.gif',
            spelling: phonemes['i'].associated,
            name: 'Elevación',
            nature: 'phoneme',
            category: 'WP',
            dificulty: 3,
            description: 'Partiendo a la altura de la cadera y con la palma hacia arriba, se eleva verticalmente la mano aproximadamente a la altura de la barbilla',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Elevar.webp',
            animation: '/src/assets/gestures/animations/Elevar.webm'
        },
        'o' : {
            phoneme: 'o',
            placeholder: '/src/assets/gestures/placeholders/Circunferencia.webp',
            gif: '/src/assets/gestures/gifs/Circunferencia.gif',
            spelling: phonemes['o'].associated,
            name: 'Circunferencia',
            nature: 'phoneme',
            category: 'P',
            dificulty: 2,
            description: 'Con los dedos extendidos y apuntando hacia arriba se dibuja una circunferencia iniciando el recorrido hacia adentro (hacia al pecho).',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Circunferencia.webp',
            animation: '/src/assets/gestures/animations/Circunferencia.webm'
        },
        'u' : {
            phoneme: 'u',
            placeholder: '/src/assets/gestures/placeholders/Balanceo.webp',
            gif: '/src/assets/gestures/gifs/Balanceo.gif',
            spelling: phonemes['u'].associated,
            name: 'Balanceo',
            nature: 'phoneme',
            category: 'P',
            dificulty: 2,
            description: 'Partiendo de la altura de las costillas con el codo ligeramente más flexionado de 90 grados y los dedos apuntando al frente, se dibuja una depresión hacia la izquierda (como un tazón poco profundo) y se regresa con una depresión hacia la derecha',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Balanceo.webp',
            animation: '/src/assets/gestures/animations/Balanceo.webm'
        },
        'p' : {
            phoneme: 'p',
            placeholder: '/src/assets/gestures/placeholders/Doble_golpe.webp',
            gif: '/src/assets/gestures/gifs/Doble_golpe.gif',
            spelling: phonemes['p'].associated,
            name: 'Doble golpe',
            nature: 'phoneme',
            category: 'WP',
            dificulty: 3,
            description: 'Con la mano derecha en puño y a la altura del corazón, y la izquierda con la palma hacia arriba a la altura del ombligo, se baja la derecha golpeando dos veces en la mano izquierda y regresa a la altura original',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Doble_golpe.webp',
            animation: '/src/assets/gestures/animations/Doble_golpe.webm'
        },
        'poɾ ké' : {
            phoneme: 'poɾ ké',
            placeholder: '/src/assets/gestures/placeholders/Doble_golpe.webp',
            gif: '/src/assets/gestures/gifs/Doble_golpe.gif',
            spelling: ['¿Por qué?'],
            name: 'Doble golpe',
            nature: 'word',
            category: 'WP',
            dificulty: 3,
            description: 'Con la mano derecha en puño y a la altura del corazón, y la izquierda con la palma hacia arriba a la altura del ombligo, se baja la derecha golpeando dos veces en la mano izquierda y regresa a la altura original',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Doble_golpe.webp',
            animation: '/src/assets/gestures/animations/Doble_golpe.webm'
        },
        'b' : {
            phoneme: 'b',
            placeholder: '/src/assets/gestures/placeholders/Vamos.webp',
            gif: '/src/assets/gestures/gifs/Vamos.gif',
            spelling: phonemes['b'].associated,
            name: 'Indicación',
            nature: 'phoneme',
            category: 'WP',
            dificulty: 2,
            description: 'Con la mano derecha a la altura de la cadera y la izquierda a la altura de la barbilla, se realiza un movimiento como corte vertical en sentidos contrarios, la derecha sube a la barbilla y la izquierda baja a la cadera. Por un instante a medio camino ambas manos se rozan',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Vamos.webp',
            animation: '/src/assets/gestures/animations/Vamos.webm'
        },
        /* 'none' : {
            phoneme: 'none',
            placeholder: '/src/assets/gestures/placeholders/Vamos.webp',
            gif: '/src/assets/gestures/gifs/Vamos.gif',
            spelling: ['-'],
            name: 'Indicación',
            nature: 'word',
            category: 'WP',
            dificulty: 2,
            description: 'Con la mano derecha a la altura de la cadera y la izquierda a la altura de la barbilla, se realiza un movimiento como corte vertical en sentidos contrarios, la derecha sube a la barbilla y la izquierda baja a la cadera. Por un instante a medio camino ambas manos se rozan',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Vamos.webp',
            animation: '/src/assets/gestures/animations/Vamos.webm'
        }, */
        't' : {
            phoneme: 't',
            placeholder: '/src/assets/gestures/placeholders/Corte.webp',
            gif: '/src/assets/gestures/gifs/Corte.gif',
            spelling: phonemes['t'].associated,
            name: 'Corte',
            nature: 'phoneme',
            category: 'WP',
            dificulty: 3,
            description: 'Con la mano derecha tocando el costado izquierdo de la cadera y la palma viendo hacia abajo, se realiza un corte horizontal hacia la derecha con una pequeña inclinación hacia arriba',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Corte.webp',
            animation: '/src/assets/gestures/animations/Corte.webm'
        },
        /* 'none' : {
            phoneme: 'none',
            placeholder: '/src/assets/gestures/placeholders/Corte.webp',
            gif: '/src/assets/gestures/gifs/Corte.gif',
            spelling: ['-'],
            name: 'Corte',
            nature: 'word',
            category: 'WP',
            dificulty: 3,
            description: 'Con la mano derecha tocando el costado izquierdo de la cadera y la palma viendo hacia abajo, se realiza un corte horizontal hacia la derecha con una pequeña inclinación hacia arriba',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Corte.webp',
            animation: '/src/assets/gestures/animations/Corte.webm'
        }, */
        'd' : {
            phoneme: 'd',
            placeholder: '/src/assets/gestures/placeholders/Idear.webp',
            gif: '/src/assets/gestures/gifs/Idear.gif',
            spelling: phonemes['d'].associated,
            name: 'Pensamiento',
            nature: 'phoneme',
            category: 'WP',
            dificulty: 3,
            description: 'Con la palma de la mano derecha entornada a medio camino hacia el pecho y a la altura del corazón, sube tocando con las yemas de los dedos la sección derecha de la frente y luego extiende hacia el frente y ligeramente hacia afuera para terminar con los dedos extendidos apuntando al frente',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Idear.webp',
            animation: '/src/assets/gestures/animations/Idear.webm'
        },
        /* 'none' : {
            phoneme: 'none',
            placeholder: '/src/assets/gestures/placeholders/Idear.webp',
            gif: '/src/assets/gestures/gifs/Idear.gif',
            spelling: ['-'],
            name: 'Pensamiento',
            nature: 'word',
            category: 'WP',
            dificulty: 3,
            description: 'Con la palma de la mano derecha entornada a medio camino hacia el pecho y a la altura del corazón, sube tocando con las yemas de los dedos la sección derecha de la frente y luego extiende hacia el frente y ligeramente hacia afuera para terminar con los dedos extendidos apuntando al frente',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Idear.webp',
            animation: '/src/assets/gestures/animations/Idear.webm'
        }, */
        'k' : {
            phoneme: 'k',
            placeholder: '/src/assets/gestures/placeholders/Exclamacion.webp',
            gif: '/src/assets/gestures/gifs/Exclamacion.gif',
            spelling: phonemes['k'].associated,
            name: 'Exclamación',
            nature: 'phoneme',
            category: 'WP',
            dificulty: 3,
            description: 'Con las yemas de los dedos tocándose y las palmas mirando hacia el estómago, se abren los brazos en sentido contrario de manera que las palmas se entornan ligeramente hacia arriba y hacia afuera',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Exclamacion.webp',
            animation: '/src/assets/gestures/animations/Exclamacion.webm'
        },
        'dónde' : {
            phoneme: 'dónde',
            placeholder: '/src/assets/gestures/placeholders/Exclamacion.webp',
            gif: '/src/assets/gestures/gifs/Exclamacion.gif',
            spelling: ['¿Dónde?'],
            name: 'Exclamación',
            nature: 'word',
            category: 'WP',
            dificulty: 3,
            description: 'Con las yemas de los dedos tocándose y las palmas mirando hacia el estómago, se abren los brazos en sentido contrario de manera que las palmas se entornan ligeramente hacia arriba y hacia afuera',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Exclamacion.webp',
            animation: '/src/assets/gestures/animations/Exclamacion.webm'
        },
        'g' : {
            phoneme: 'g',
            placeholder: '/src/assets/gestures/placeholders/Medio_circulo.webp',
            gif: '/src/assets/gestures/gifs/Medio_circulo.gif',
            spelling: phonemes['g'].associated,
            name: 'Medio círculo',
            nature: 'phoneme',
            category: 'WP',
            dificulty: 3,
            description: 'Con las yemas de los dedos tocándose y las palmas mirando hacia adentro a la altura del abdomen, se marca un medio círculo con cada mano para finalizar tocandose las yemas de los dedo otra vez a la altura de la barbilla',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Medio_circulo.webp',
            animation: '/src/assets/gestures/animations/Medio_circulo.webm'
        },
        /* 'none' : {
            phoneme: 'none',
            placeholder: '/src/assets/gestures/placeholders/Medio_circulo.webp',
            gif: '/src/assets/gestures/gifs/Medio_circulo.gif',
            spelling: ['-'],
            name: 'Medio círculo',
            nature: 'word',
            category: 'WP',
            dificulty: 3,
            description: 'Con las yemas de los dedos tocándose y las palmas mirando hacia adentro a la altura del abdomen, se marca un medio círculo con cada mano para finalizar tocandose las yemas de los dedo otra vez a la altura de la barbilla',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Medio_circulo.webp',
            animation: '/src/assets/gestures/animations/Medio_circulo.webm'
        }, */
        'ʧ' : {
            phoneme: 'ʧ',
            placeholder: '/src/assets/gestures/placeholders/Aplauso_doble.webp',
            gif: '/src/assets/gestures/gifs/Aplauso_doble.gif',
            spelling: phonemes['ʧ'].associated,
            name: 'Aplauso doble',
            nature: 'phoneme',
            category: 'WP',
            dificulty: 3,
            description: 'Con las manos en los costados se realizan 2 aplausos y se termina el movimiento con las manos juntas después del segundo aplauso',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Aplauso_doble.webp',
            animation: '/src/assets/gestures/animations/Aplauso_doble.webm'
        },
        /* 'none' : {
            phoneme: 'none',
            placeholder: '/src/assets/gestures/placeholders/Aplauso_doble.webp',
            gif: '/src/assets/gestures/gifs/Aplauso_doble.gif',
            spelling: ['-'],
            name: 'Aplauso doble',
            nature: 'word',
            category: 'WP',
            dificulty: 3,
            description: 'Con las manos en los costados se realizan 2 aplausos y se termina el movimiento con las manos juntas después del segundo aplauso',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Aplauso_doble.webp',
            animation: '/src/assets/gestures/animations/Aplauso_doble.webm'
        }, */
        'f' : {
            phoneme: 'f',
            placeholder: '/src/assets/gestures/placeholders/Chop_chop.webp',
            gif: '/src/assets/gestures/gifs/Chop_chop.gif',
            spelling: phonemes['f'].associated,
            name: 'Chop Chop',
            nature: 'phoneme',
            category: 'WP',
            dificulty: 3,
            description: 'Con la mano a 45 grados y tocando la barbilla se realizan 2 movimientos como cortes hacia al frenteChop_chop.webp',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Chop_chop.webp',
            animation: '/src/assets/gestures/animations/Chop_chop.webm'
        },
        /* 'none' : {
            phoneme: 'none',
            placeholder: '/src/assets/gestures/placeholders/Chop_chop.webp',
            gif: '/src/assets/gestures/gifs/Chop_chop.gif',
            spelling: ['-'],
            name: 'Chop Chop',
            nature: 'word',
            category: 'WP',
            dificulty: 3,
            description: 'Con la mano a 45 grados y tocando la barbilla se realizan 2 movimientos como cortes hacia al frenteChop_chop.webp',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Chop_chop.webp',
            animation: '/src/assets/gestures/animations/Chop_chop.webm'
        }, */
        's' : {
            phoneme: 's',
            placeholder: '/src/assets/gestures/placeholders/Sentimiento.webp',
            gif: '/src/assets/gestures/gifs/Sentimiento.gif',
            spelling: phonemes['s'].associated,
            name: 'Sentimiento',
            nature: 'phoneme',
            category: 'WP',
            dificulty: 3,
            description: 'Tocando con la puntas de los dedos el pecho al nivel del corazón se marca un círculo iniciando a la izquierda',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Sentimiento.webp',
            animation: '/src/assets/gestures/animations/Sentimiento.webm'
        },
        /* 'none' : {
            phoneme: 'none',
            placeholder: '/src/assets/gestures/placeholders/Sentimiento.webp',
            gif: '/src/assets/gestures/gifs/Sentimiento.gif',
            spelling: ['-'],
            name: 'Sentimiento',
            nature: 'word',
            category: 'WP',
            dificulty: 3,
            description: 'Tocando con la puntas de los dedos el pecho al nivel del corazón se marca un círculo iniciando a la izquierda',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Sentimiento.webp',
            animation: '/src/assets/gestures/animations/Sentimiento.webm'
        }, */
        'x' : {
            phoneme: 'x',
            placeholder: '/src/assets/gestures/placeholders/Cruzar.webp',
            gif: '/src/assets/gestures/gifs/Cruzar.gif',
            spelling: phonemes['x'].associated,
            name: 'Entrecruzado',
            nature: 'phoneme',
            category: 'P',
            dificulty: 1,
            description: 'Se dibuja una x partiendo de la altura del hombro derecho, después al costado de la cadera izquierda, sube a la altura del hombro izquierdo y finaliza en el costado derecho de la cadera',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Cruzar.webp',
            animation: '/src/assets/gestures/animations/Cruzar.webm'
        },
        'j' : {
            phoneme: 'j',
            placeholder: '/src/assets/gestures/placeholders/Yo.webp',
            gif: '/src/assets/gestures/gifs/Yo.gif',
            spelling: phonemes['j'].associated,
            name: 'Propio',
            nature: 'phoneme',
            category: 'WP',
            dificulty: 3,
            description: 'Con los dedos extendidos y el brazo tocando el bolsillo derecho, se sube el brazo y se toca el pecho a la altura del corazón',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Yo.webp',
            animation: '/src/assets/gestures/animations/Yo.webm'
        },
        'io' : {
            phoneme: 'io',
            placeholder: '/src/assets/gestures/placeholders/Yo.webp',
            gif: '/src/assets/gestures/gifs/Yo.gif',
            spelling: ['yo'],
            name: 'Propio',
            nature: 'word',
            category: 'WP',
            dificulty: 3,
            description: 'Con los dedos extendidos y el brazo tocando el bolsillo derecho, se sube el brazo y se toca el pecho a la altura del corazón',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Yo.webp',
            animation: '/src/assets/gestures/animations/Yo.webm'
        },
        'm' : {
            phoneme: 'm',
            placeholder: '/src/assets/gestures/placeholders/Costados.webp',
            gif: '/src/assets/gestures/gifs/Costados.gif',
            spelling: phonemes['m'].associated,
            name: 'Costados',
            nature: 'phoneme',
            category: 'P',
            dificulty: 2,
            description: 'Con la mano apuntando al frente y a la mitad del pecho, se marca un cuarto de arco hacia la izquierda bajando a la altura de las costillas y se regresa con un medio arco a la derecha que sube a la altura del pecho y finaliza en las costillas derechas',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Costados.webp',
            animation: '/src/assets/gestures/animations/Costados.webm'
        },
        'n' : {
            phoneme: 'n',
            placeholder: '/src/assets/gestures/placeholders/Agitado.webp',
            gif: '/src/assets/gestures/gifs/Agitado.gif',
            spelling: phonemes['n'].associated,
            name: 'Agitado',
            nature: 'phoneme',
            category: 'WP',
            dificulty: 3,
            description: 'Con la mano a la altura del hombro derecho, se agita dos veces de derecha a izquierda y de regreso',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Agitado.webp',
            animation: '/src/assets/gestures/animations/Agitado.webm'
        },
        /* 'none' : {
            phoneme: 'none',
            placeholder: '/src/assets/gestures/placeholders/Agitado.webp',
            gif: '/src/assets/gestures/gifs/Agitado.gif',
            spelling: ['-'],
            name: 'Agitado',
            nature: 'word',
            category: 'WP',
            dificulty: 3,
            description: 'Con la mano a la altura del hombro derecho, se agita dos veces de derecha a izquierda y de regreso',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Agitado.webp',
            animation: '/src/assets/gestures/animations/Agitado.webm'
        }, */
        'ɲ' : {
            phoneme: 'ɲ',
            placeholder: '/src/assets/gestures/placeholders/Medio_corazon.webp',
            gif: '/src/assets/gestures/gifs/Medio_corazon.gif',
            spelling: phonemes['ɲ'].associated,
            name: 'Medio corazón',
            nature: 'phoneme',
            category: 'WP',
            dificulty: 2,
            description: 'Se parte de la mitad del pecho y se realiza un semicírculo hacia afuera a la altura del inicio de las costilla y el hombro, después de baja con una inclinación de 45 grados hacia el ombligo',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Medio_corazon.webp',
            animation: '/src/assets/gestures/animations/Medio_corazon.webm'
        },
        /* 'none' : {
            phoneme: 'none',
            placeholder: '/src/assets/gestures/placeholders/Medio_corazon.webp',
            gif: '/src/assets/gestures/gifs/Medio_corazon.gif',
            spelling: ['-'],
            name: 'Medio corazón',
            nature: 'word',
            category: 'WP',
            dificulty: 2,
            description: 'Se parte de la mitad del pecho y se realiza un semicírculo hacia afuera a la altura del inicio de las costilla y el hombro, después de baja con una inclinación de 45 grados hacia el ombligo',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Medio_corazon.webp',
            animation: '/src/assets/gestures/animations/Medio_corazon.webm'
        }, */
        'l' : {
            phoneme: 'l',
            placeholder: '/src/assets/gestures/placeholders/Doble_latido.webp',
            gif: '/src/assets/gestures/gifs/Doble_latido.gif',
            spelling: phonemes['l'].associated,
            name: 'Latido doble',
            nature: 'phoneme',
            category: 'WP',
            dificulty: 3,
            description: 'Con la palma tocando el pecho a la altura del corazón, se despega unos centímetros y se vuelve a tocar en 2 ocasiones',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Doble_latido.webp',
            animation: '/src/assets/gestures/animations/Doble_latido.webm'
        },
        /* 'none' : {
            phoneme: 'none',
            placeholder: '/src/assets/gestures/placeholders/Doble_latido.webp',
            gif: '/src/assets/gestures/gifs/Doble_latido.gif',
            spelling: ['-'],
            name: 'Latido doble',
            nature: 'word',
            category: 'WP',
            dificulty: 3,
            description: 'Con la palma tocando el pecho a la altura del corazón, se despega unos centímetros y se vuelve a tocar en 2 ocasiones',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Doble_latido.webp',
            animation: '/src/assets/gestures/animations/Doble_latido.webm'
        }, */
        'ɾ' : {
            phoneme: 'ɾ',
            placeholder: '/src/assets/gestures/placeholders/Revolver.webp',
            gif: '/src/assets/gestures/gifs/Revolver.gif',
            spelling: phonemes['ɾ'].associated,
            name: 'Meneo',
            nature: 'phoneme',
            category: 'WP',
            dificulty: 2,
            description: 'Con la mano derecha arriba y la izquierda abajo, se giran en sentidos contrarios(hacia afuera y hacia atrás respectivamente) completando una circunferencia y vuelven a la misma altura en la que se empezó',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Revolver.webp',
            animation: '/src/assets/gestures/animations/Revolver.webm'
        },
        /* 'none' : {
            phoneme: 'none',
            placeholder: '/src/assets/gestures/placeholders/Revolver.webp',
            gif: '/src/assets/gestures/gifs/Revolver.gif',
            spelling: ['-'],
            name: 'Meneo',
            nature: 'word',
            category: 'WP',
            dificulty: 2,
            description: 'Con la mano derecha arriba y la izquierda abajo, se giran en sentidos contrarios(hacia afuera y hacia atrás respectivamente) completando una circunferencia y vuelven a la misma altura en la que se empezó',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Revolver.webp',
            animation: '/src/assets/gestures/animations/Revolver.webm'
        }, */
        'r' : {
            phoneme: 'r',
            placeholder: '/src/assets/gestures/placeholders/Recorrer.webp',
            gif: '/src/assets/gestures/gifs/Recorrer.gif',
            spelling: phonemes['r'].associated,
            name: 'Impulso',
            nature: 'phoneme',
            category: 'WP',
            dificulty: 3,
            description: 'Con la palma mirando al frente y cerca del pecho, se hace un gesto de empujar hacia adelante',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Recorrer.webp',
            animation: '/src/assets/gestures/animations/Recorrer.webm'
        },
        /* 'none' : {
            phoneme: 'none',
            placeholder: '/src/assets/gestures/placeholders/Recorrer.webp',
            gif: '/src/assets/gestures/gifs/Recorrer.gif',
            spelling: 'none',
            name: 'Impulso',
            nature: 'word',
            category: 'WP',
            dificulty: 3,
            description: 'Con la palma mirando al frente y cerca del pecho, se hace un gesto de empujar hacia adelante',
            animationPlaceholder: '/src/assets/gestures/animation_placeholders/Recorrer.webp',
            animation: '/src/assets/gestures/animations/Recorrer.webm'
        }, */
    }
}